//
// Created by markus on 05.04.21.
//

#ifndef MR_CPP_CODE_CONSTANTS_H
#define MR_CPP_CODE_CONSTANTS_H

const double CALCULATION_RESOLUTION = 1.0;
const double GAME_TPS = 10;
const double GAME_SPEED_MODIFIER = 1; // this will modify the time calculated for one game loop step. A value of 2 will cause an acceleration of game speed by 2. This means 2 seconds will be calculated in one second, but it will look to the game like 2 seconds passed.
const std::string SIMULATOR_WINDOW_NAME = std::string("Robot simulator");
const double NOISE_MODIFIER = 1; // allows to modify the amount of noise generated by sensors. Set to 0 to disable noise

const int NOVELTY_THRESHOLD = 80;  // novelty threshold for novelty detection in robot operator

#endif //MR_CPP_CODE_CONSTANTS_H
